// schemas/group.schema.ts
import { z } from "zod";

interface GlobalAttributeLookup {
  id: string;
  name: string;
}

export const createProductGroupSchema = (globalAttributes: GlobalAttributeLookup[]) => {
  return z.object({
    id: z.string().optional(),
    name: z.string().min(1, "Product group designation name is required"),
    skuPattern: z
      .string()
      .min(1, "SKU template formula structure cannot be empty"),
    skuSeparator: z.string(),
    description: z.string().nullable().optional(),
    brandId: z.string().nullable().optional().or(z.literal("")),
    categoryId: z.string().nullable().optional().or(z.literal("")),
    isActive: z.boolean(),
    tags: z.array(z.string()),
    itemType: z.string().min(1, "Item type name is required"),
    trackExpiry: z.boolean(),
    trackLots: z.boolean(),
    trackSerials: z.boolean(),
    features: z.array(
      z.object({
        key: z.string().min(1, "Label/Key is required"),
        value: z.string().min(1, "Specification is required")
      })
    ),
    options: z.array(
      z.object({
        name: z.string().min(1, "Option name cannot be empty"),
        attributeId: z.string(), // Assuming dynamic/custom options might use a specific ID like "custom" or empty
        isDriver: z.boolean(),
        values: z.array(
          z.object({
            value: z.string().min(1, "Value cannot be empty"),
            isSkuDriver: z.boolean(),
          })
        ).min(1, "At least one tag value is required for this option"),
      })
    ).min(1, "You must provide at least one variant option attribute to create a group"),

    variants: z.array(
      z.object({
        productId: z.string(),       // Product inflowId
        variantId: z.string(),       // ProductVariant inflowId
        sku: z.string(),
        name: z.string(),
        defaultPrice: z.number().or(z.string()),
        isExisting: z.boolean(),     // True if pulled from the DB, false if newly generated by Cartesian changes
        status: z.enum(["active", "unlink", "delete"]), // 👈 Action tracking state
      })
    ),
    images: z.array(
      z.object({
        id: z.string().optional(),
        originalUrl: z.string().min(1, "Original image link is required").url("Must be valid asset media CDN source URL"),
        largeUrl: z.union([z.literal(""), z.string().url("Must be valid asset media CDN source URL")]).nullable().optional(),
        mediumUncroppedUrl: z.union([z.literal(""), z.string().url("Must be valid asset media CDN source URL")]).nullable().optional(),
        mediumUrl: z.union([z.literal(""), z.string().url("Must be valid asset media CDN source URL")]).nullable().optional(),
        smallUrl: z.union([z.literal(""), z.string().url("Must be valid asset media CDN source URL")]).nullable().optional(),
        thumbUrl: z.union([z.literal(""), z.string().url("Must be valid asset media CDN source URL")]).nullable().optional(),
      })
    ).optional().nullable(),
  })
  .superRefine((data, ctx) => {
    const seenAttributeIds = new Set<string>();
    const seenNames = new Set<string>();

    // Lowercase names of global attributes for case-insensitive matching
    const globalNamesLower = globalAttributes.map(attr => attr.name.toLowerCase());

    if (data.options.some(opt => opt.isDriver)) {
      if (data.skuPattern && !data.skuPattern.includes("[BRAND]")) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: "Your SKU template layout must contain the '[BRAND]' anchor variable tag.",
          path: ["skuPattern"],
        });
      }  
    }

    data.options.forEach((option, index) => {
      const normalizedName = option.name.trim().toLowerCase();

      // 1. Prevent duplicate selected global classes/attributes (skip custom/empty IDs if allowed)
      if (option.attributeId && option.attributeId !== "custom" && option.attributeId !== "") {
        if (seenAttributeIds.has(option.attributeId)) {
          ctx.addIssue({
            code: z.ZodIssueCode.custom,
            message: "This global attribute has already been selected",
            path: ["options", index, "attributeId"],
          });
        }
        seenAttributeIds.add(option.attributeId);
      }

      // 2. Prevent duplicate custom/inline names within the current form submission
      if (seenNames.has(normalizedName)) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: "Duplicate option name found in this group",
          path: ["options", index, "name"],
        });
      }
      seenNames.add(normalizedName);

      // 3. Prevent typing a custom name that matches a registered global attribute
      // Only enforce this if the user is treating it as a custom input (e.g., attributeId is empty or marked custom)
      const isCustomInput = !option.attributeId || option.attributeId === "custom" || option.attributeId === "";
      if (isCustomInput && globalNamesLower.includes(normalizedName)) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: "This option name matches a global attribute. Please select it from the list instead.",
          path: ["options", index, "name"],
        });
      }
    });
  });
};

// Default export type placeholder
export type ProductGroupInput = z.infer<ReturnType<typeof createProductGroupSchema>>;